### ISSUE TITLE
Setup Failed

### ISSUE THREAD

**Issue by drpeek** [nyuvis/patient-viz#60]
HI, I was installing the repository on Ubuntu, and the setup process proceeds to some extent and then gives me the following error when it reaches the step where it says, downloading NDC definitions. 
Thanks
downloading sample 10
######################################################################## 100,0%
replace DE1_0_2008_Beneficiary_Summary_File_Sample_10.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
######################################################################## 100,0%
replace DE1_0_2008_to_2010_Carrier_Claims_Sample_10A.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
######################################################################## 100,0%
replace DE1_0_2008_to_2010_Carrier_Claims_Sample_10B.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
######################################################################## 100,0%
replace DE1_0_2008_to_2010_Inpatient_Claims_Sample_10.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
######################################################################## 100,0%
replace DE1_0_2008_to_2010_Outpatient_Claims_Sample_10.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
######################################################################## 100,0%
replace DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_10.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
######################################################################## 100,0%
replace DE1_0_2009_Beneficiary_Summary_File_Sample_10.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
######################################################################## 100,0%
replace DE1_0_2010_Beneficiary_Summary_File_Sample_10.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
done downloading samples
downloading NDC definitions
######################################################################## 100,0%
[tmp.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of tmp.zip or
        tmp.zip.zip, and cannot find tmp.zip.ZIP, period.
setup failed!

**Comment by JosuaKrause** [comment]
hmm, i suspect the NDC link doesn't work anymore. they probably changed the link. note that those are just example files. if you want to use your own data you don't need those

**Comment by JosuaKrause** [comment]
I updated the URL. should work now

**Comment by drpeek** [comment]
Thanks a lot!
